name: CI/CD for Spring Boot

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build project with Gradle
        run: ./gradlew build

      - name: Run Spring Boot application
        run: ./gradlew bootRun
